version: '3.8'

services:
  backend:
    image: giahuyday/cm_nestjs
    container_name: backend
    restart: always
    depends_on:
      - postgres
    environment: 
      DB_HOST: host.docker.internal  
      DB_PORT: 54321
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_DATABASE: cm_nest
      PORT: 3001
      ALLOW_ORIGIN: http://localhost:3000,
      ALLOW_HEADER: Content-Type,Accept,Authorization,
      ALLOW_METHOD: GET,HEAD,PUT,PATCH,POST,DELETE,
    ports:
      - "3001:3001"

  frontend:
    image: giahuyday/cm_nextjs
    container_name: frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001/graphql
      NEXT_PUBLIC_PERM: admin
      PORT: 3000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cm_nest
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: