import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

import Sidebar from "@/components/SideBar";
import Header from "@/components/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background-lg`}>
                <header className="h-[50px] w-full backdrop-blur-sm border-b-[1px] flex items-center justify-between px-4 py-2 text-white">
                    <Header />
                </header>
                <div id="side-bar" className="md:grid grid-cols-9">
                    <div className="md:grid md:col-span-2 xs:hidden h-full backdrop-blur-sm border-r-[1px]">
                        <Sidebar />
                    </div>
                    <div className="md:col-span-7 sm:col-span-9 justify-items-center backdrop-blur-sm">{children}</div>
                </div>
            </body>
        </html>
    );
}
